library/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.authors, name='authors'),
    path('authors/<int:author_id>', views.author, name='author'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('search/', views.search, name='search'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('mybooks/<uuid:pk>', views.BookByUserDetailView.as_view(), name='my-book'),
    path('mybooks/new', views.BookByUserCreateView.as_view(), name='my-borrowed-new'),
    path('mybooks/<uuid:pk>/update', views.BookByUserUpdateView.as_view(), name='my-book-update'),
    path('mybooks/<uuid:pk>/delete', views.BookByUserDeleteView.as_view(), name='my-book-delete'),
    path('i18n/', include('django.conf.urls.i18n')),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include('library.urls')),
    path('', RedirectView.as_view(url='library/', permanent=False)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

library/models.py
from django.db import models
import uuid
from django_resized import ResizedImageField
from django.contrib.auth.models import User
from datetime import date
from tinymce.models import HTMLField
from PIL import Image
from django.utils.translation import gettext_lazy as _

class Genre(models.Model):
    """For genre table in database"""
    genre_id = models.AutoField(primary_key=True)
    name = models.CharField(_('Name'), max_length=100, help_text=_('Enter type of genre: '))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Genre')
        verbose_name_plural = _('Genres')

class Author(models.Model):
    author_id = models.AutoField(primary_key=True)
    first_name = models.CharField(_('First name'), max_length=100)
    last_name = models.CharField(_('Last name'), max_length=100)
    # Simple, base text editor.
#    description = models.TextField('Description', max_length=2000, default='')

    # Gives us more capabilities to format text in admins site.
    description = HTMLField()
    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return f"{self.first_name} - {self.last_name}"

    def display_books(self):
        return ', '.join(book.title for book in self.books.all())

class Book(models.Model):
    book_id = models.AutoField(primary_key=True)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, related_name='books')
    title = models.CharField(_('Title'), max_length=200, help_text=_('Enter book title: '))
    description = models.TextField(_('Description'), max_length=1000, help_text=_('Enter short book description: '))
    isbn = models.CharField(
        'ISBN', max_length=13,
        help_text='13 Symbol <a href="https://www.isbn-international.org/content/what-isbn">ISBN kodas</a>')
    genre = models.ManyToManyField(Genre, help_text=_('Enter books genre: '))
    cover = ResizedImageField(_('Cover'), size=[300, 400], upload_to='covers', null=True)


    def __str__(self):
        return self.title

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all())


class BookInstance(models.Model):
    instance_id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique book UUID code')
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    due_back = models.DateField('Available', null=True, blank=True)
    # Choice fields ALWAYS in CAPITAL
    LOAN_STATUS = (
        ('p', 'Processing'),
        ('t', 'Taken'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    book_status = models.CharField(max_length=1, default='a', blank=True, choices=LOAN_STATUS, help_text='Book status')
    reader = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ['due_back']



    def __str__(self):
        return f"{self.book.title}"


class BookReview(models.Model):
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True, blank=True)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Review', max_length=2000)

    class Meta:
        verbose_name = "Review"
        verbose_name_plural = 'Reviews'
        ordering = ['-date_created']


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(default="profile_pics/default.png", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} profile"

    # photo resize
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.photo.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.photo.path)

library/forms.py
from .models import BookReview, Profile, BookInstance
from django import forms
from django.contrib.auth.models import User

class BookReviewForm(forms.ModelForm):
    class Meta:
        model = BookReview
        fields = ('content', 'book', 'reviewer',)
        widgets = {'book': forms.HiddenInput(), 'reviewer': forms.HiddenInput()}

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['photo']

class DateInput(forms.DateInput):
    input_type = 'date'

class UserBookCreateForm(forms.ModelForm):
    class Meta:
        model = BookInstance
        fields = ['book', 'reader', 'due_back']
        widgets = {'reader': forms.HiddenInput(), 'due_back': DateInput()}

library/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .models import Genre, Author, Book, BookInstance
from django.views import generic
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.forms import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from .forms import BookReviewForm, UserUpdateForm, ProfileUpdateForm, UserBookCreateForm
from django.views.generic.edit import FormMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.utils.translation import gettext as _



# Class based
class BookListView(generic.ListView):
    model = Book
    # You can set a variable name for the template yourself
    context_object_name = 'my_book_list'
    # get a list of 3 books with the word 'The' in the title
  #  queryset = Book.objects.filter(title__icontains='The')[:3]
    paginate_by = 2
    # We have already used this one. You have no idea what default path it creates :)
    template_name = 'book_list.html'


# Ar galima ir taip:
# class BookListView(generic.ListView):
#     model = Book
#
#     def get_queryset(self):
#         return Book.objects.filter(title__icontains='The')[:3]

    # def get_context_data(self, **kwargs):
    #         context = super(BookListView, self).get_context_data(**kwargs)
    #         context['duomenys'] = 'eilutė iš lempos'
    #         return context


class BookDetailView(FormMixin, generic.DetailView):
    model = Book
    template_name = 'book_detail.html'
    form_class = BookReviewForm

    # we indicate where we will end up if the comment succeeds.
    def get_success_url(self):
        return reverse('book-detail', kwargs={'pk': self.object.book_id})

    # standard rewrite of the post method using FormMixin.
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    # here we specify that the book will be exactly the one under which we comment, and the user will be the one who is logged in.
    def form_valid(self, form):
        form.instance.book = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(BookDetailView, self).form_valid(form)

def index(request):
    # Count number of books and book instances
    book_count = Book.objects.all().count()
    book_instance_count = BookInstance.objects.all().count()
    # Count number of available books (with status 'a')
    available_books_count = BookInstance.objects.filter(book_status__exact='a').count()
    # Count number of authors
    author_count = Author.objects.all().count()

    # With the additional variable num_visits and load it into the context.
    visits_count = request.session.get('visits_count', 1)
    request.session['visits_count'] = visits_count + 1
    context = {
        'books': book_count,
        'book_instances': book_instance_count,
        'authors': author_count,
        'available': available_books_count,
        'visits': visits_count,
    }

    return render(request, "index.html", context)


# Function based
def authors(request):
    paginator = Paginator(Author.objects.all(), 2)
    page_number = request.GET.get('page')
    paged_authors = paginator.get_page(page_number)
    return render(request, 'authors.html', context={'authors': paged_authors})

def author(request, author_id):
    single_author = get_object_or_404(Author, pk=author_id)
    return render(request, 'author.html', {'author': single_author})

def search(request):
    """
    Simple search. query gets information from search box,
    search_results filters book titles and descriptions based on the entered text.
    Icontains differs from contains in that icontains ignores upper/lower case letters.
    """
    query = request.GET.get('query')
    search_results = Book.objects.filter(Q(title__icontains=query) | Q(description__icontains=query) |
                                         Q(author__first_name__icontains=query) | Q(author__last_name__icontains=query))
    return render(request, 'search.html', {'books': search_results, 'query': query})




#-------------------------cRud---------------------------------------
class LoanedBooksByUserListView(LoginRequiredMixin, ListView):
    model = BookInstance
    context_object_name = 'books'
    template_name = 'user_books.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(reader=self.request.user).order_by('due_back')


class BookByUserDetailView(LoginRequiredMixin, DetailView):
    model = BookInstance
    template_name = 'user_book.html'


class BookByUserCreateView(LoginRequiredMixin, CreateView):
    model = BookInstance
    #fields = ['book', 'due_back']
    success_url = "/library/mybooks/"
    template_name = 'user_book_form.html'
    form_class = UserBookCreateForm

    def form_valid(self, form):
        form.instance.reader = self.request.user
        return super().form_valid(form)

    def get_absolute_url(self):
        """Specifies the final address of a specific description"""
        return reverse('book-detail', args=[str(self.instance_id)])


class BookByUserUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = BookInstance
    fields = ['book', 'due_back']
    success_url = "/library/mybooks/"
    template_name = 'user_book_form.html'

    def form_valid(self, form):
        form.instance.reader = self.request.user
        return super().form_valid(form)

    def test_func(self):
        book = self.get_object()
        return self.request.user == book.reader


class BookByUserDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = BookInstance
    success_url = "/library/mybooks/"
    template_name = 'user_book_delete.html'

    def test_func(self):
        book = self.get_object()
        return self.request.user == book.reader

#----------------------User-Registration-----------------------------
@csrf_protect
def register(request):
    if request.method == "POST":
        # take values from registration form
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # checking if the passwords matches
        if password == password2:
            # checking if the username is not taken
            if User.objects.filter(username=username).exists():
                messages.error(request, _(f'The username {username} is taken!'))
                return redirect('register')
            else:
                # checking if the email does not exist
                if User.objects.filter(email=email).exists():
                    messages.error(request, _(f'The user with email {email} already registered!'))
                    return redirect('register')
                else:
                    # if everything ok, creates new user
                    User.objects.create_user(username=username, email=email, password=password)
                    messages.info(request, _(f'User {username} has been registered!'))
                    return redirect('login')
        else:
            messages.error(request, _('Passwords do not match!'))
            return redirect('register')
    return render(request, 'registration/register.html')


#----------------------------------------------------

@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, _(f"Profile has been updated"))
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'profile.html', context)


#----------------------------------------------------

library/templates/author.html
{% extends "base.html" %}

{% block content %}
    <div class="container author">
    <h4>{{ author.first_name }} {{ author.last_name }}</h4>
    <hr/>
    <p>{{ author.description | safe }}</p>
    </hr>
    </br>
    <h5>We have these {{ author.first_name }} {{ author.last_name }} books:</h5>
    {% for i in author.books.all %}
       <li>{{ i.title }}</li> 
    {% endfor %}
    </div>
{% endblock %}

library/templates/authors.html
{% extends "base.html" %}

{% block content %}
  <h1>Authors</h1>
  <p>The list of authors.</p>
    {% for a in authors %}
      <li><a href="{% url 'author' a.author_id %}">{{a.first_name}} {{a.last_name}}</a></li>
    {% endfor %}

<div class="container pages">
    <nav aria-label="...">
        {% if authors.has_other_pages %}
            <ul class="pagination pagination-sm justify-content-end">
                {% for i in authors.paginator.page_range %}
                    {% if authors.number == i %}
                        <li class="page-item active">
                            <a class="page-link">{{ i }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}
    </nav>
</div>
{% endblock %}

library/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Public library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}


      {% load i18n %}
      <form action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
        <input name="next" type="hidden" value="{{ redirect_to }}"/>
        <select name="language" onchange="this.form.submit()">
          {% load static %}
          {% get_current_language as LANGUAGE_CODE %}
          {% get_available_languages as LANGUAGES %}
          {% for lang in LANGUAGES %}
          <option style="background-image: url({% static 'img/lt.png' %});" value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %} selected="selected" {% endif %}>
            {{ lang.1 }}
          </option>
          {% endfor %}
        </select>
      </form>


        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'books' %}">All books</a></li>
          <li><a href="{% url 'authors' %}">All authors</a></li>
          <li>
            <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0">
              <input name="query" class="form-control" type="text" placeholder="Search">
            </form>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'profile' %}">
              <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
              </svg>
            {{ user.get_username }}</a></li>
            <li class="nav-item"><a class="nav-link" href="#">You are logged in as: {{ user.get_username }}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'my-borrowed'%}">My books</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'my-borrowed-new'%}?next=/library">New</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}?next=/library">Logout</a></li>
          {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Login</a></li>
          {% endif %}
          {% if not user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'register'%}">Register</a></li>
          {% endif %}
        </ul>
          {% if messages %}
                  {% for message in messages %}
                      <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'info' %}success{% endif %}" role="alert">
                              {{ message }}
                      </div>
                  {% endfor %}
          {% endif %}
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

library/templates/book_detail.html
{% extends "base.html" %}

{% block content %}
  <img src="{{ book.cover.url }}" style="margin-bottom: 20px;">
  <h1>{{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{% url 'author' book.author.pk %}">{{ book.author }}</a></p>
  <p><strong>Description:</strong> {{ book.description }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>
  </br>
  <h4>Reviews:</h4>
  {% if book.bookreview_set.all %}
    {% for review in book.bookreview_set.all %}
      <hr>
      <strong>{{ review.reviewer }}</strong>, <em>{{ review.date_created}}</em>
      <p>{{ review.content }}</p>
    {% endfor %}
  {% else %}
    <p>The book has no reviews</p>
  {% endif %}

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies:</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.book_status == 'a' %}text-success{% elif copy.book_status == 't' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_book_status_display }}
      </p>
      {% if copy.book_status != 'a' %}
        <p><strong>Will be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p class="text-muted"><strong>Id:</strong> {{ copy.instance_id }}</p>
    {% endfor %}
  </div>
    {% if user.is_authenticated %}
  <div class="fieldWrapper">
    <hr><br/>
    <h4>Leave a review:</h4>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.content }}</br>
      <input type="submit" value="Save">
    </form>
  </div>
  {% endif %}
{% endblock %}

library/templates/book_list.html
{% extends "base.html" %}

{% block content %}
   {% load static %}
    <h1>Book list</h1></br>
    {% if object_list %}
    <div class="row">
      {% for book in object_list %}
        <div class="col-md-4 d-flex align-items-stretch">
          <div class="card mb-4 shadow-sm">
            {% if book.cover %}
              <img src="{{ book.cover.url }}" class="card-img-top book-cover" alt="...">
            {% else %}
              <img src="{% static 'media/covers/no-image.png' %}" class="card-img-top book-cover">
            {% endif %}
            <div class="card-body">
              <h6 class="card-subtitle mb-2 text-muted">{{ book.author }}</h6>
              <p class="card-text"><a href="{{ book.book_id }}">{{ book.title }}</a></p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    {% else %}
      <p>No books in library.</p>
    {% endif %}

  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">back</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} from {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">forward</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

library/templates/index.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Public library" %}</h1>
    <p>{% trans "Welcome to the paradise of books!" %}</p>
    <p>{% trans "At the moment available:" %}</p>
    <ul>
        <li><strong>{% trans "Books:" %}</strong> {{ books }}</li>
        <li><strong>{% trans "Book instance:" %}</strong> {{ book_instances }}</li>
        <li><strong>{% trans "Available:" %}</strong> {{ available }}</li>
        <li><strong>{% trans "Authors:" %}</strong> {{ authors }}</li>
    </ul>
    <p>{% trans "You came here" %} {{ visits }} {% trans "time." %}</p>

{% endblock %}

library/templates/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.photo.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock %}

library/templates/search.html
{% extends "base.html" %}

{% block content %}
  <h1>Search by "{{query}}" result:</h1>
  </br>
  {% if books %}
  <ul>
    {% for book in books %}
      <li>
        <a href="{% url 'book-detail' book.book_id %}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Oops. Nothing found :(</p>
  {% endif %}

  {% endblock %}

library/templates/user_book.html
{% extends "base.html" %}

{% block content %}
    <h1>My taken book:</h1>
    <hr>
        <ul>
        <img class="rounded-circle" src="{{object.book.cover.url}}">
        <li><strong class="{% if object.is_overdue %}text-danger{% endif %}">Book name: {{object.book.title}}</strong></li>
        <li><strong>Return by:</strong> {{object.due_back}}</li>
            {% if object.reader == user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'my-book-update' object.instance_id %}">Update</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'my-book-delete' object.instance_id %}">Delete</a>
            </div>
            {% endif %}
        <br/>
      </li>
    </ul>
{% endblock %}

library/templates/user_book_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete instance</legend>
            <h2>Are you sure you want to delete the book {{ object.uuid }} instance?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'my-book' object.instance_id %}">Undo</a>
        </div>
    </form>
    </div>
{% endblock %}

library/templates/user_book_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">New book instance</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Save</button>
        </div>
    </form>
    </div>
{% endblock %}

library/templates/user_books.html
{% extends "base.html" %}

{% block content %}
    <h1>Mano paimtos knygos</h1>
    <img class="rounded-circle" src="{{user.profile.photo.url}}">
    {% if books %}
        {% for bookinst in books %}
    <hr>
        <ul>
        <li><strong class="{% if bookinst.is_overdue %}text-danger{% endif %}">Book name: {{bookinst.book.title}}</strong></li>
        <li><strong>Return by:</strong> {{bookinst.due_back}}</li>
        <br/>
        <a class="btn btn-primary" href="{{ bookinst.pk }}" role="button">Review</a>
      </li>

    </ul>
{% endfor %}
    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}